### ISSUE TITLE
Build errors when not using sterling-supplicant

### ISSUE THREAD

**Issue by kekiefer** [LairdCP/meta-laird-cp#2]
I'm trying to build an image without sterling-supplicant, and getting hit with the following:

    The recipe sterling-supplicant is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
      /mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/pkgdata/jetson-xavier/runtime/wpa-supplicant-passphrase.packaged
    (matched in manifest-jetson_xavier-wpa-supplicant.packagedata)
      /mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/pkgdata/jetson-xavier/runtime/wpa-supplicant-passphrase
    (matched in manifest-jetson_xavier-wpa-supplicant.packagedata)
      /mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/pkgdata/jetson-xavier/runtime/wpa-supplicant-cli.packaged
    (matched in manifest-jetson_xavier-wpa-supplicant.packagedata)
      /mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/pkgdata/jetson-xavier/runtime/wpa-supplicant-cli
        (matched in manifest-jetson_xavier-wpa-supplicant.packagedata)
    Please verify which recipe should provide the above files.
    ...

Explicitly setting PREFERRED_PROVIDER for wpa-supplicant-cli and wpa-supplicant-passphrase to be wpa-supplicant doesn't help. Removing these packages from the sterling-supplicant recipe does solve the problem, so this doesn't seem to be working the way it should. Others that RDEPEND on these packages don't know where to get them from.

Should these packages with names wpa-supplicant-passphrase and wpa-supplicant-cli really be created by the sterling-supplicant recipe? Or should these packages instead be named sterling-supplicant-passphrase and sterling-supplicant-cli and then be RRECOMMENDED by sterling-supplicant?

**Comment by borkra** [comment]
You probably did not set PREFERRED_PROVIDER correctly, it works for me.

These package names are correct, they should be wpa_supplicant_xxx. Sterling supplicant is wpa_supplicant with all the security updates, which we maintain. 

It is recommended to use sterling_supplicant not wpa_supplicant. wpa_supplicant that comes with the Yocto layer is probably old and not maintained, as Yocto project moved on to different release.

**Comment by kekiefer** [comment]
My setting PREFERRED_PROVIDER to sterling_supplicant works fine. The trouble comes when building for configurations where I want to use upstream wpa_supplicant instead, for whatever reason, but the meta-laird layer is still in place. For example, not every configuration we're building uses laird parts, or for any other reason. This layer needs to play nicely with others.

The structure of this recipe is such that it breaks the auxiliary wpa-supplicant-tools and wpa-supplicant-cli packages from the upstream wpa_supplicant recipe. I should be able to set PREFERRED_PROVIDER back to wpa-supplicant-* for these auxiliary -passphrase and -cli packages if I want to, but I can't because this recipe is incorrect.

The reason that this recipe is wrong is because it does not RPROVIDES/RREPLACES for these auxiliary packages with a new package name, in the way it does with the main wpa_supplicant package and the new sterling_supplicant package. This recipe creates packages with the same names as the upstream wpa_supplicant recipe (wpa-supplicant-cli and wpa-supplicant-passphrase), so there are conflicts when both the wpa_supplicant and sterling_supplicant recipes are trying to build them.

It seems that perhaps this could be solved simply by creating new sterling-supplicant-* packages, and then have the RRECOMMENDS_sterling_supplicant pull in the custom sterling-supplicant-passphrase and sterling-supplicant-cli packages.

**Comment by borkra** [comment]
Ok, I will fix this.

**Comment by kekiefer** [comment]
Thanks, the fix in 49bef5c54 works. Can this be ported to the 7.0.0.x branch and kept it in place moving forward?

**Comment by borkra** [comment]
It is in 7.0.0.x branch.

**Comment by kekiefer** [comment]
Not here on github it isn't

**Comment by borkra** [comment]
Ok, we pushed it to github.
