### ISSUE TITLE
meta-laird-cp brcmfmac takes too long time(~130 sec) to the load firmware on 5.4.47 while booting

### ISSUE THREAD

**Issue by Rutvij-dev** [LairdCP/meta-laird-cp#4]
Hi,
I am working on imx8qxp mek on zeus-5.4.47, which has 5.4.47 Linux kernel.

I have used this meta-laird-cp as i have laird sterling lwb5 wi-fi, bt chip.
This meta layer got successfully build and provided .ko, as well as gets installed in my system also.

After insertion of .ko its working good and creates wlan0 node.

But my issue is brcmfmac is taking too much time(~130 sec) to load the wi-fi firmware and then it creates wlan0 node for further work.

Below are my boot-up time logs

> [    8.200899] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4339-sdio for chip BCM4339/2
[    8.229241] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac4339-sdio.fsl,imx8qxp-aiml-ei.txt failed with error -2
[    8.251658] brcmfmac mmc0:0001:1: Falling back to sysfs fallback for: brcm/brcmfmac4339-sdio.fsl,imx8qxp-aiml-ei.txt
[   68.865104] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4339-sdio for chip BCM4339/2
[  130.079786] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-11), device may have limited channels available
[  130.095330] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4339/2 wl0: Sep  9 2019 12:24:31 version 6.37.39.114 (r722401 CY)

So what could be the issue here ?

Any help would be appreciable.

Thanks

**Comment by borkra** [comment]
This does not look right: "brcm/brcmfmac4339-sdio.fsl,imx8qxp-aiml-ei.txt"

You obviously not using the LWB firmware that we provide. 

Please use one of the lwb5 firmware packages from this layer. You will need to download firmware from lairdconnect.com website, and acknowledge the legal stuff.

To get this to work you need to:
- remove complete bluetooth and Wi-Fi stack, and reenable all required crypto for backported subsystems to work (ECDH, CMAC, AES, SHA256, and some others) from kernel config and rebuild the kernel.
- remove all brcm firmware installed by linux-firmware recipe or provided by NXP. And use the firmware packages from this layer.

For future questions please contact our support team at support@lairdconnect.com

**Comment by john-nosky** [comment]
The driver is pulling "fsl,imx8qxp-aiml-ei" from the compatible string of the parent node because a MMC device subnode was not used. This is fine as it falls back to the generic firmware filename. I confirmed the firmware version number reported in the OP is from the 8.2.0.16 release.

I am assuming the slow load is platform related. As stated above, feel free to open a support case, but please use our support portal instead of direct email:
[https://www.lairdconnect.com/resources/support](https://www.lairdconnect.com/resources/support)

**Comment by borkra** [comment]
@john-nosky what more worries me is "brcmf_c_process_clm_blob: no clm_blob available", I believe our firmware distribution  has clm blob. Thus my assessment of incorrect firmware.

**Comment by john-nosky** [comment]
@borkra This is true for the LWB and LWB5plus, but the LWB5 does not come with a clm_blob file.
