### ISSUE TITLE
File do already exist - what to choose in PREFERED_PROVIDER?

### ISSUE THREAD

**Issue by FLSCHI** [LairdCP/meta-laird-cp#5]
Hello,

the below error is shown when using meta-laird-cp layer for a Sterling-LWB module. 

I followed your SIG and removed the cfg and wifi modules from the kernel and I added the PREFERRED_PROVIDER and the IMAGE_INSTALL things. 

Any suggestions what to do to get a image packaged?

Thanks,
Florian

ERROR: linux-ti-staging-4.14.69+gitAUTOINC+56d5512a87-r22c.arago5 do_packagedata_setscene: The recipe linux-ti-staging is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-bluetooth-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-hci-uart-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-rfcomm-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-bluetooth-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-cfg80211-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-cfg80211-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-rfcomm-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-hci-uart-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
Please verify which recipe should provide the above files.

The build has stopped, as continuing in this scenario WILL break things - if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would, however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error, however switching DISTRO_FEATURES on an existing build directory is not supported - you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.
ERROR: linux-ti-staging-4.14.69+gitAUTOINC+56d5512a87-r22c.arago5 do_packagedata_setscene: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.

**Comment by borkra** [comment]
As README specifies, you need to:

 - To use Wi-Fi driver add "backports-laird" and appropriate firmware recipe
   to your image
   **1. Remove cfg80211, mac80211, bluetooth from the kernel config
   2. Explicitly add the cfg80211, mac80211, bluetooth  dependencies (mostly crypto) to the kernel config**

I.e. you need to run menuconfig and/or change defconfig for your kernel.

If you require more support, please contact Technical Support directly:
https://www.lairdconnect.com/resources/support

**Comment by borkra** [comment]
Here is the quick example how to make kernel config changes using menuconfig in Yocto:

bitbake -c clean virtual/kernel
bitbake -c menuconfig virtual/kernel
bitbake <image name>

**Comment by FLSCHI** [comment]
Hello Boris,

thanks for your fast reply. 

Following please find, what I did:
> 1. Remove cfg80211, mac80211, bluetooth from the kernel config

1. I removed the following in the kernel config as described in the SIG
- Networking support -> Wireless -> cfg80211 -> set to n
- Device Drivers -> Network device support -> Wireless LAN -> set to n

> 2. Explicitly add the cfg80211, mac80211, bluetooth dependencies (mostly crypto) to the kernel config

2. I don’t know what exactly to do here. Can you be more precise what to choose in the kernel config.

Further it would help a lot, to provide the correct kernel.cfg file in your meta-layer to exclude/include these configs, because the steps above would always have to be done manual when a clean or cleanall got executed. So couldn’t this be done like described here https://www.yoctoproject.org/docs/1.6.1/kernel-dev/kernel-dev.html <https://www.yoctoproject.org/docs/1.6.1/kernel-dev/kernel-dev.html> in chapter 2.2.3 by using a .cfg file?

Anyway, even when I do the described things above, the build still stops.

I did a 
bitbake -c cleanall virtual/kernel
bitbake -c cleansstate virtual/kernel
bitbake -c clean virtual/kernel

Then I excluded the things of step 1.
Don’t know what to do in step 2. Please could you be more precise. 

Then ran a bitbake image again, but build stops in the kernel build while trying the task do_package.

As you can see in the error message below, it’s not about cfg80211 or mac80211 but it’s about bluetooth, hci_uart, rfcomm which collide with your meta-layer. 

Thanks for your help, 
Florian
ERROR: linux-ti-staging-4.14.69+gitAUTOINC+56d5512a87-r22c.arago5 do_packagedata: The recipe linux-ti-staging is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-bluetooth-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-hci-uart-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-rfcomm-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-bluetooth-4.14.69+
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-rfcomm-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
  /home/build/yocto/build/tmp-glibc/pkgdata/icg-connect-am3354/runtime/kernel-module-hci-uart-4.14.69+.packaged
    (matched in manifest-icg-connect-am3354-lwb-backports-laird.packagedata)
Please verify which recipe should provide the above files.

**Comment by borkra** [comment]
1. There is no generically "correct" cfg, every CPU vendor require different cfg as chip hardware different, and then there are application differences, requiring certain features to be enabled, and then there are different kernel versions that change cfg as well. Bottom line one needs to configure his kernel for his application.
2. Please open support ticket at https://www.lairdconnect.com/resources/support, so our FAEs can assist you further.
