### ISSUE TITLE
Any plans to support Kerne V5.10.35 ?

### ISSUE THREAD

**Issue by Rutvij-dev** [LairdCP/meta-laird-cp#7]
Hi Folks,
I have been through the release note for Sterling-LWB5+, where it is mentioned for the support section from Kernel v4.1 to 5.4.

I am using Kernel v5.10.35(yocto hardkknot)

So any plans to support this ?
If not now, can anyone guide us to do it ourselves?

Appreciate the help/

--
Thanks,

**Comment by borkra** [comment]
Kernel 5.10 support for LWB will be released soon.

Please direct all technical and general inquiries to our support ticketing system:
[Support inquiries](https://www.lairdconnect.com/contact?form_type=Support)
