### ISSUE TITLE
PREMIRRORS and MIRRORS are disabled?

### ISSUE THREAD

**Issue by skycaptain** [LairdCP/meta-laird-cp#8]
We're using `PREMIRRORS` to cache download artifacts on a local server. Downloads from that server are not only faster but also more reliable (e.g. consider [Github's outage end of November](https://www.githubstatus.com/history)). With that regard `PREMIRRORS` are a very common use-case to share cache download artifacts in the local network.

With https://github.com/LairdCP/meta-laird-cp/commit/088af94b40b21550aae128c80486ae3264d3db82 a change was introduced that disables `MIRRORS` and `PREMIRRORS` for basically all the recipes provided by this metalayer. Since we don't cache the download directory during builds, but only use our local server with `PREMIRRORS`, this change forces a download from github.com on every build. From the commit message it's not clear to me why `PREMIRRORS` and `MIRRORS` are unset, as they are usually only appended in recipes and unset only in special use-cases by endusers of a metalayer.

Can you please clarify why this setting is set like this? Could it be a leftover from debugging and unintentionally commited?

**Comment by borkra** [comment]
They are unset so that Yocto does not try to contact Yocto project mirrors.  It wastes a lot of time and no benefits, as these files are never on Yocto project mirrors.

Are cleaning local download cache?  
Local download cache should take care of download every time issue.

**Comment by borkra** [comment]
Just making sure, everybody download correct stuff from the official download server, not from unknown source.

One can always overwrite mirror setting locally, if desired and your build system is fancy enough to create your own mirrors.

**Comment by skycaptain** [comment]
From [Yocto's manual:](https://www.yoctoproject.org/docs/current/mega-manual/mega-manual.html#source-mirrors)

> Pre-mirrors are appropriate when you have a shared directory that is not a directory defined by the DL_DIR variable. A Pre-mirror typically points to a shared directory that is local to your organization.

We are using PREMIRRORS to share the download cache across multiple machines during builds. We don't cache/store the DL_DIR during builds.

>  It wastes a lot of time and no benefits...

I wrote the benefits of having PREMIRRORS in a local network above. From my experience I can not tell a difference in speed, i.e. "waste of time".

> Just making sure, everybody download correct stuff from the official download server, not from unknown source.

Your're right that the truth comes from the official server; however Bitbake is using checksums to ensure the downloaded files are valid. Do you have reason not to trust the default premirrors? From my understanding it's left to the end user to trust these sources or not.

> One can always overwrite mirror setting locally, if desired and your build system is fancy enough to create your own mirrors.

We set PREMIRRORS in our distro .conf (just like Poky), however the value from the recipe takes precedence, overrides the value from the distro .conf and finally breaking the use-case.

**Comment by borkra** [comment]
> I wrote the benefits of having PREMIRRORS in a local network above. From my experience I can not tell a difference in speed, i.e. "waste of time".

Try to do it when file is not on the server or the server is down, Yocto tries, github , then mirror 1, then mirror 2, then mirror 3 and only then fails. That is especially problem when we download internal releases.

> We set PREMIRRORS in our distro .conf (just like Poky), however the value from the recipe takes precedence, overrides the value from the distro .conf and finally breaking the use-case.

One can always overwrite recipe setting from local.conf: PREMIRRORS_\<recipe name\> = "xxxx"

**Comment by skycaptain** [comment]
> Try to do it when file is not on the server or the server is down, Yocto tries, github , then mirror 1, then mirror 2, then mirror 3 and only then fails.

Yes, but at least several servers are tried. However, when you disable PREMIRRORS and MIRRORS completely and Github is down (just like last week for several hours), Yocto has no chance of trying other servers, but fails and hence blocking developers for hours.

> That is especially problem when we download internal releases. where there is no checksum.

Would it be possible to disable the PREMIRRORS setting for your internal releases/builds only? FWIU your concerns are about your development workflow, so setting this option only in your builds, would allow other users of this metalayers to continue using PREMIRRORS as usual.

> One can always overwrite recipe setting from local.conf: PREMIRRORS_<recipe name> = "xxxx"

I might also use `_forcevariable`, which I havn't tested yet, but both solutions are hacky and uncommon with regard to expected default behaviour.

**Comment by borkra** [comment]
> Would it be possible to disable the PREMIRRORS setting for your internal releases/builds only? FWIU your concerns are about your development workflow, so setting this option only in your builds, would allow other users of this metalayers to continue using PREMIRRORS as usual.

Unfortunately default PREMIRRORS is what we are trying to avoid. We will think about this not sure what will come up.

**Comment by borkra** [comment]
Ok, we allowed PREMIRRORS.
